version: '3'
services:
    db:
        image: postgres:13
        container_name: postgres-db
        restart: always
        environment:
            - POSTGRES_DB=cryptopayments
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1234

        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data

    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        depends_on:
            - db

volumes:
    postgres_data:
